version: '2'

services:
    web_db:
        image: mariadb:latest
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql:/var/lib/mysql
    web:
        image: nginx:mainline
        container_name: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./www:/var/www/html:rw
            - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./logs/nginx:/var/log/nginx:rw
            - ./run/:/run/
    web_fpm:
        build: .
        container_name: php_fpm
        depends_on:
            - web_db
        volumes:
            - ./www:/var/www/html
            - ./run/:/run/:rw
    web_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - web_fpm
            - web_db
        ports:
            - 8181:80
        environment:
            - PMA_HOST=web_db
volumes:
    mysql:

